#version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: monex-app
        restart: unless-stopped
        volumes:
            - ./:/var/www/html/hr-system
        ports:
            - "9000:80"
        networks:
            - monex-network
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: monex-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: monex_db
            MYSQL_ROOT_PASSWORD: '@Dmin2021!'
            MYSQL_ROOT_HOST: '%'  # Allow connections from any host
        command: --default-authentication-plugin=mysql_native_password
            --bind-address=0.0.0.0
        ports:
            - "3307:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - monex-network

networks:
    monex-network:

volumes:
    mysql-data:
