services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: monex-app
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
        ports:
            - "80:80"
        networks:
            - monex-network

    mysql:
        image: mysql:8.0
        container_name: monex-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: monex_db
            MYSQL_ROOT_PASSWORD: your_root_password
            MYSQL_USER: monex_user
            MYSQL_PASSWORD: your_user_password
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - monex-network

networks:
    monex-network:

volumes:
    mysql-data:
