services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: monexhub_app
        volumes:
            - .:/var/www/html/hr-system
        ports:
            - "9000:9000"
        networks:
            - monexhub-net

networks:
    monexhub-net:
