services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: monex-app
        restart: unless-stopped
        volumes:
            - ./:/var/www/html/hr-system
        ports:
            - "9000:80"
        networks:
            - monex-network

    mysql:
        image: mysql:8.0
        container_name: monex-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: monex_db
            MYSQL_ROOT_PASSWORD: '@Dmin2021!'
        ports:
            - "3307:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - monex-network

networks:
    monex-network:

volumes:
    mysql-data:
